    double summa(double a, double b)
    double sub(double a, double b)
    double mult(double a, double b)
    double dev(double a, double b)
    double pow(double a, double b) 
    double sqrt(double a)
